---
title: "Homework_5_Kyle_Hancock"
author: "Kyle Hancock"
date: "11/21/2019"
output: word_document
---

```{r  global_options}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error = FALSE)
```

``` {r read homicide data in}
library(readr)
homicides <- read_csv(file = "homicide-data.csv")
```

```{r baltimore data}
library(lubridate)
library(tidyverse)
library(forcats)
baltimore <- homicides %>% 
  filter(city == "Baltimore") %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  mutate_at(vars(reported_date), funs(year, month, day)) %>% 
  group_by(year, month) %>% 
  summarize(total = n()) %>% 
  mutate(date = paste(month, year, sep = "-15-"),
         date = mdy(date)) %>% 
  mutate(winter_vs_summer = month(date) %in% c("11", "12", "1", "2", "3", "4"), 
         winter_vs_summer = factor(winter_vs_summer,
                                   levels = c(FALSE, TRUE),
                                   labels = c("Summer", "Winter")))
```

```{r Figure}
library(ggplot2)
baltimore %>% 
  ggplot(aes(x = date, y = total)) +
  geom_col(aes(fill = winter_vs_summer)) +
  geom_vline(xintercept = ymd("2015-4-12"), color = "red", linetype = 2, size = 1.2) +
  geom_text(aes(x = ymd("2015-4-12"), label = "Arrest of \n Freddie Gray", y = 40), color = "gray80",
            hjust = "right") +
  geom_smooth(span = .1, se = FALSE) +
  labs(x = "Date", y = "Monthly homicides", fill = "", title = "Homicides in Baltimore, MD")
```